### ISSUE TITLE
Unable to view certificate after issuing it

### ISSUE THREAD

**Issue by erwinsg** [OpenCerts/opencerts-documentation#12]
Hi,

I am unable to view the certificate using opencerts website (localhost) after issuing it. Error message is displayed in the website : The certificate has not been issued.

Please refer to attached file for your reference.
[SIT_20181113.docx](https://github.com/OpenCerts/opencerts-documentation/files/2575279/SIT_20181113.docx)

**Comment by yehjxraymond** [comment]
Hi Erwin,

Seemed like your contract store is using an old ABI. We have migrated from that store about two weeks ago (you deployed this one ~59 days ago). There is no backward compatibility for that store as there was a major upgrade.

Can you deploy another instance of the store and issue the certificate again? 

Thank you.

Cheers,
Raymond



Notes:
Contract Store: https://ropsten.etherscan.io/address/0x20bc9c354a18c8178a713b9bccffac2152b53990

**Comment by erwinsg** [comment]
Hi Raymond,
Seems like transaction hash can't be found, is it due to slowness at ropsten website.

https://ropsten.etherscan.io/tx/0x4acf815d9928d5c0b8df0dc86f49fc97e859d15bb41a651a3247e9e99ee90a81

**Comment by rjchow** [comment]
From the transaction logs it looks like you issued the same batch twice, the second of which failed (misreported as a success - I'll put down a ticket to fix this). I'm not really sure how you got the above transaction hash, it could be interesting to investigate this if you have more information

I can't get your certificate json file out of the .docx, but if its a cert with the merkle root `25fb0ec9c1262c21db76f25b77817d23cde7e1f68e566fa3439387d94b393649`, as far as I can tell it should be a success, have you pulled the latest changes for your local opencerts repo? Otherwise you can try verifying on https://dev.opencerts.io

[0] First tx https://ropsten.etherscan.io/tx/0x8e75db429bd5a71e1d94c642b81a6dac403d7cf6436db427271cad22df41d48e
[1] Second tx https://ropsten.etherscan.io/tx/0xa62985defc7ba20926dac8b5d0bda1d083f88131d24ddbcd9f2751110d356094

**Comment by erwinsg** [comment]
Hi Raymond,

Today i tried again but i am still unable to view the certificate. Attached is the screen capture (SIT_20181114_1.docx) and the signed certificate (SITCerts_PC1_00000016_singedCert.zip) for your reference.

For the second transaction that supposed to be failed yesterday, can please let me know what other information do you need to investigate?

[SITCerts_PC1_00000016_singedCert.zip](https://github.com/OpenCerts/opencerts-documentation/files/2578788/SITCerts_PC1_00000016_singedCert.zip)

[SIT_20181114_1.docx](https://github.com/OpenCerts/opencerts-documentation/files/2578809/SIT_20181114_1.docx)

Thank you.

**Comment by erwinsg** [comment]
hi Raymond,

Thanks for your reply and it is okay now after sync the latest code from repo.
