### ISSUE TITLE
Unable to view eCert using the custom templates format

### ISSUE THREAD

**Issue by erwinsg** [OpenCerts/opencerts-documentation#13]
Hi,

I am unable to view the eCert which has been issued using the custom templates. Is it due to this warnings: 
"Issuer identity cannot be verified"?

Please refer to attached file for your reference.

[SIT_20181114_2.docx](https://github.com/OpenCerts/opencerts-documentation/files/2579500/SIT_20181114_2.docx)

[SITCerts_PC1_00000016.zip](https://github.com/OpenCerts/opencerts-documentation/files/2579498/SITCerts_PC1_00000016.zip)

**Comment by yehjxraymond** [comment]
The warning has nothing to do with the visuals.

Your certificates are using the template "SITCerts" which is not created. You need to create a template that resolves "SITCerts".

Please refer to Ngee Ann's folder at `src/components/CertificateTemplates/NgeeAnnPolytechnic`. Once you have created a template, resolve it by altering the ``src/components/CertificateTemplates/index.js` to resolve for your template.

Will recommend you to use one template instead of the multiple template they are using.

**Comment by erwinsg** [comment]
Hi Raymond,

Thanks for the quick response. I noted that part of my code (opencerts-website\src\components\CertificateTemplates\index.js) is updated after sync with repo.

**Comment by yehjxraymond** [comment]
We are looking at your fork and there isn't any code change from ours. Can you push your code to your master branch and we take a look at it?

**Comment by erwinsg** [comment]
hi Raymond,

I am still doing development, pending clarifications from user for some items. After I completed the development, I will push my changes.

Thank you.
