### ISSUE TITLE
Certificate CLI tool

### ISSUE THREAD

**Issue by yenhocktan** [OpenCerts/opencerts-documentation#28]
Your documentation on Certificate CLI tools indicates that there are functions to deploy certificate store and commit certificate batch on certificate store. However, when executing the commands, I'm getting "unknown arguments: commit". Please advise.

**Comment by rjchow** [comment]
Apologies the readme.md on that repository has not been updated to reflect changes, we have moved those functions to a publicly available UI at https://admin.opencerts.io

More details on contract store and issuance at https://github.com/OpenCerts/opencerts-documentation/blob/master/deploying_store.md and https://github.com/OpenCerts/opencerts-documentation/blob/master/issuing_certificates.md

You may assume that the information in this repository supersedes that of all the other repositories, again apologies for that

**Comment by yenhocktan** [comment]
Thanks. Now that the functions are available via the admin UI, is there any way to automate this?

**Comment by rjchow** [comment]
During our development process we decided that blockchain transactions should ideally not be automated as it means the private key has to be made available without a human in the loop, hence the decision to move it to a UI.

The contract store deployment is one-off per institute so that's not too arduous, and the workflow of issuance does indicate that the registrar's office should be in the loop when issuing. This requires one interaction per batch of issuance
