### ISSUE TITLE
Concerns on the "Recovery of Issuer Account"

### ISSUE THREAD

**Issue by thannehene** [OpenCerts/opencerts-documentation#42]
The ultimate recovery of Crypto-Wallets is based on the availability of Passphrase words/Wallet seeds. As the OpenCert uses the Hardware-Wallet, the passphrase of 24 words are the ultimate key to the recovery of the crypto-accounts bound to the Participating Institutions. 
It is also recommended to jointly kept these words, at least under the custody of 2 persons.

However, in case of unexpected incidents (such as a fire, or etc) where these words are totally lost and unable to uncover, the only option that I can see is the use of a "New Account" and go through the "Identity Registration" again. 
1. Do we have any other alternatives here?  
2. If "New Account" is the only solution; 
   a)  In case if the issuer needs to revoke a particular cert which has already issued using the initial account, how can they do this?
   b) Isn't it mandatory to cancel all the batches issued using the previous account and re-issue them with the new account?
   c) Also, it is true that the issues cert can still get verified if there is no requirement to revoke any individual certs in the future [after losing the account]. Correct me if I'm wrong.
3. Are there any other ways to recovery such accounts using the Identity Registration?

**Comment by rjchow** [comment]
1) You may take two approaches either separately or in combination here
a. technologically, you may administer the certificate store using a multisig contract - we do not have documentation for this at this point in time nor have we tested such a procedure, but it is theoretically and practically feasible (lots of prior art on google)
b. on the policy level, you may duplicate the 24 words and safekeep them, perhaps under the custody of a 3rd party with no vested interest, for example a bank safe deposit box.

2) a) They will not be able to do this without implementing one or both of the above approaches
b) It is not mandatory to revoke all previously issued batches if you are certain that control of the certificate store has not fallen into another party's hands and that means in c) they will still be verifiable.

3) No

If you have any suggestions for improvement please do explain so that we can improve our processes

**Comment by thannehene** [comment]
First, looking at the existing solution and the above explanations, we can conclude the followings:
For "1.": We do not have any other alternatives in the existing solution. 
   Therefore, the only option is to re-initiate the process with a "New Account ... & Re-Register in Identity Registry & etc.” [However, your suggestion "1.b" seems simple to enable within the existing solution.]
   
For "2.": b) **Even it is not possible to revoke the entire batch** as the "a)" is not possible already. 
  However, as it is potentially valid [biz-case] to revoke the individual-certs, having the previous batch uncontrolled [for revocation] is miss leading. Therefore, irrespective of the certainty of the certificate store's new custodian & even they are still verifiable, upon confirming the permanent loss of the existing account, it is necessary to revoke (or at least change its view rendering to differentiate) all the previous batches-of-certs issued using that lost account. [Suggestion for View handle: “A)” below]

Secondly, the followings are some suggestions:
A)	To handle the Revocation of all the previously issued cert-batches [in case of a permanent loss of the account], the existing open-cert-web app can invalidate the relevant custom-template/s to avoid showing a valid-view in their verifications or enable a prompt to handle this scenario. In addition, it can keep another list of “$template” tags [as the "revoked-templates"] and generalize the view for those certs routing to the "revoked-templates", and to show a meaningful message such as "Invalidated by the institution. Please contact your HR to gain the new certs." or etc. 
In parallel, the institute has to re-issue all the previous certs with a new template-name ["$template"].
B)	Also, I think the Multi-owner smart contract can be used along with a 3rd party custodian to revoke & reissue certs. But, this looks far towards the readiness considering the existing already usable solution, & also the fact that some institutions are already on-board.

I hope the above workaround will resolve the missing solution to handle the permanent loss of the Hardware-Wallets [due to whatever reasons]. In that case, it doesn't really matter even if the device has fallen into another party's hand, but it is urgent to verify the loss and inform the "open-cert-web portal" for the invalidation.

**Comment by rjchow** [comment]
That is an excellent suggestion, I will add it to our contingency documentation - we can invalidate certificate store using the template whitelist (revoking the whole template probably wouldn't work because some or most institutes aren't using a new template per issuance)

As for using a multi-owner smart contract for institutes that have already deployed, that is still possible as the certificate store ownership can be transferred by its current owner.

Thank you for your thoughts!
