### ISSUE TITLE
Official cert images in open platform 

### ISSUE THREAD

**Issue by yvonneyong** [OpenCerts/opencerts-documentation#63]
Have concerns been raised that official imagery eg. logos and signatures would be publicly available either in the OpenCerts repository or the JSON files? Is there any long term plan to make the OpenCerts repository have more access control?

**Comment by yehjxraymond** [comment]
The current recommendation is to store it in the opencert file itself. That level of 'security' is aking to having the person's signature on the hardcopy certificate that the students own currently. Logically you can have something that is public but not. 

That said, there is always an option to **not include a signature** in the certificate since it does not serve to make the certificate more authentic or secure.
