### ISSUE TITLE
Unregistered institution

### ISSUE THREAD

**Issue by yvonneyong** [OpenCerts/opencerts-documentation#65]
Could we clarify the rationale behind allowing the certificate to be rendered when the institution is not registered on OpenCerts? Since anyone can deploy a cert store, create json files, batch sign and issue them, would it be possible not to allow the certs to be displayed. Or if there is a strong case to allow the certs from unregistered institutions to be viewed, can the "Unknown Institution" tag when the certificate is rendered be made more obvious, eg. in bold red colour, etc?

**Comment by wmclaxton** [comment]
@yvonneyong This is to enable institutions which are not providing courses that are not either MOE or private academies eligible for Skills Future funding (basically the rest of the world) to use the OpenCerts technology.  However the messaging is wrong, as pointed out in my issue 67 (https://github.com/OpenCerts/opencerts-documentation/issues/67). 

It is my view that rendering and verification should be entirely separate anyway.  The template document should not need to be hosted in order to verify a certificate, as it is the data payload being verified and not the layout.

**Comment by yehjxraymond** [comment]
Closing issue in view of v2.0 release
